// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj3FazDEiXd1XQeTcOPDhNwScoaEW3B28',
    appId: '1:1094239783025:web:41a58fdbf51ecf3c23f3d0',
    messagingSenderId: '1094239783025',
    projectId: 'login-73433',
    authDomain: 'login-73433.firebaseapp.com',
    storageBucket: 'login-73433.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9QYNwzVFeTvoGEvQVpjRnO2wS4Nn1uq8',
    appId: '1:1094239783025:android:9b96c51d1aeefbe223f3d0',
    messagingSenderId: '1094239783025',
    projectId: 'login-73433',
    storageBucket: 'login-73433.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwDexDKSCrp2SLsdwmg0R4G9E9nVvwjD0',
    appId: '1:1094239783025:ios:c2b5684884b86bbf23f3d0',
    messagingSenderId: '1094239783025',
    projectId: 'login-73433',
    storageBucket: 'login-73433.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwDexDKSCrp2SLsdwmg0R4G9E9nVvwjD0',
    appId: '1:1094239783025:ios:c2b5684884b86bbf23f3d0',
    messagingSenderId: '1094239783025',
    projectId: 'login-73433',
    storageBucket: 'login-73433.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj3FazDEiXd1XQeTcOPDhNwScoaEW3B28',
    appId: '1:1094239783025:web:679f0c80faccaa7823f3d0',
    messagingSenderId: '1094239783025',
    projectId: 'login-73433',
    authDomain: 'login-73433.firebaseapp.com',
    storageBucket: 'login-73433.appspot.com',
  );
}
